name: build

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
      os:
        required: true
        type: string
      debug:
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: build
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Install dependencies
        run: yarn install

      - name: Run linting
        run: yarn lint

      - name: Build
        run: yarn build
        env:
          DEBUG: ${{ inputs.debug && '*' || '' }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            cjs/
            es/
            package.json
            yarn.lock
          retention-days: 7
