name: lint

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
      os:
        required: true
        type: string

jobs:
  lint:
    name: lint
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Install dependencies
        run: yarn install

      - name: Prettier check
        run: yarn fmt:check

      - name: ESLint check
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: "."
          fail_level: error
          level: warning
