name: pr

on:
  pull_request:
    paths:
      - "src/**"
      - "package.json"
      - "yarn.lock"
      - "tsconfig*.json"
      - "eslint.config.js"
      - "vitest.config.ts"
      - ".node-version"
      - ".github/workflows/**"
      - "!**/*.md"

permissions:
  contents: read
  checks: write
  security-events: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      os: "ubuntu-latest"
      debug: false

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      os: "ubuntu-latest"

  test:
    uses: ./.github/workflows/test.yml
    needs: [build, lint]
    with:
      node-version: ${{ matrix.node-version }}
      os: ${{ matrix.os }}
      debug: false
      coverage: ${{ matrix.os == 'ubuntu-latest' && matrix.node-version == '24.x' }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        # Run only on lowest and highest supported node versions to reduce CI time
        node-version: [18.x, 24.x]
