name: pr

on: pull_request

jobs:
  build:
    name: Build and test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # Times out on GitHub CI :(
          # - macos-latest
          # - windows-latest
        node-version: [18, 19, 21]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
