name: Test

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      os:
        required: true
        type: string
      debug:
        required: false
        type: boolean
        default: false

jobs:
  test:
    name: Test
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test --reporter=verbose --reporter=junit --outputFile=test-results.xml
        env:
          DEBUG: ${{ inputs.debug && '*' || '' }}

      - name: Publish Test Results
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Vitest Tests
          path: test-results.xml
          reporter: java-junit
          fail-on-error: false
