name: test

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      os:
        required: true
        type: string
      debug:
        required: false
        type: boolean
        default: false

jobs:
  test:
    name: test
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        shell: bash
        run: yarn test
        env:
          DEBUG: ${{ inputs.debug && '*' || '' }}

      - name: List test results
        shell: bash
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in current directory:"
          ls -la
          echo "Looking for test results..."
          find . -name "*.xml" -type f 2>/dev/null || echo "No XML files found"
          find . -name "test-results.xml" -type f 2>/dev/null || echo "test-results.xml not found"

      - name: Publish Test Results
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Vitest Tests
          path: test-results.xml
          reporter: java-junit
          fail-on-error: false
